### ISSUE TITLE
Show with other field type modules in /admin/modules

### ISSUE THREAD

**Issue by kspurgin** [lyrasis/typed_labeled_fields#1]
In `/admin/modules` there is a section for field type modules: 

![image](https://user-images.githubusercontent.com/450570/148801996-a730977b-a9a3-4fcb-aee3-4db6fc3b4443.png)

This module shows up on its own in a different section:

![image](https://user-images.githubusercontent.com/450570/148802176-66734b16-1e8f-4e13-bfa6-afe018a1b3b9.png)

Ideally it would show up with the other field type modules.

**Comment by DonRichards** [comment]
OK, done.

**Comment by DonRichards** [comment]
![2022-01-10_14-16](https://user-images.githubusercontent.com/2738244/148825477-499a9a30-3f1c-4101-88a0-b40247574984.png)
